#!/bin/sh

down() {
brightnessctl s 10%-
brightness=$(light -g)
dunstify -a "BRIGHTNESS" "Decreasing to $brightness%" -h int:value:"$brightness" -i ~/.config/dunst/assets/ui/brightness_down.png -r 2593 -u normal
}

up() {
brightnessctl s +10%
brightness=$(light -g)
dunstify -a "BRIGHTNESS" "Increasing to $brightness%" -h int:value:"$brightness" -i ~/.config/dunst/assets/ui/brightness_up.png -r 2593 -u normal
}

case "$1" in
  up) up;;
  down) down;;
esac
